server:
  port: 8181

msg: Hello and Welcome to the application. You can create a new Organ by making a POST request to /api/organs endpoint. - Changes not reflected
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    # url: jdbc:mysql://docker-mysql:3306/microservices?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#      dialect: 
  application:
    name: organ-service
security:
  oauth2:
    resource:
      token-info-uri: http://172.28.43.142:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: secret  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"